{% set name = "certbot-nginx" %}
{% set version = "5.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7745fd8b2f5818b6122c35750c6db0275fe732007dc123acf1dd16e4e7a726d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - acme >=5.3.1
    - certbot >=5.6.0
    - pyopenssl >=25.0.0
    - pyparsing >=2.4.7
    - python >={{ python_min }}
    - setuptools >=41.6.0

test:
  imports:
    - certbot_nginx
    - certbot_nginx._internal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/letsencrypt/letsencrypt
  summary: Nginx plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
